name: Berlin Hack & Tell
future: true
kramdown:
  hard_wrap: true
description: >
  Berlin Hack and Tell is a monthly(ish) meetup where eight entities can show their hacks at [c-base space station](https://c-base.org) every(ish) last Tuesday of the month.

  There are 8 dynamically allocated Slots that consist of 5min presentation + 5min conversation with the audience.
  
  Follow us on [BlueSky](https://bsky.app/profile/bhnt.c-base.org), [X (fka twitter)](https://www.twitter.com/BerlinHacknTell), [Mastodon](https://chaos.social/@BHNT) or [Matrix](https://matrix.to/#/#bhnt:c-base.org).

  Check out the past projects below and sign up on our Meetup page!
url: https://berlinhackandtell.rocks
logo: /assets/images/logo.png
permalink: :year-:month-:day-:title
paginate: 100  #enables pagination, sets entries per page

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

defaults:
  -
    scope:
      layout: "slides"
    values:
      theme: "black"
      transition: "slide"
collections:
  slides:
    output: true
